In [1]:
import tensorflow as tf

2023-10-03 14:11:23.385164: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-03 14:11:24.261465: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
mask = tf.constant([[0],
                    [0],
                    [0],
                    [1],
                    [0],
                    [0],
                    [0],
                    [1],
                    [1]], dtype=tf.int32)

mask

2023-10-03 14:11:26.457002: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


<tf.Tensor: shape=(9, 1), dtype=int32, numpy=
array([[0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1]], dtype=int32)>

In [29]:
############# Daniel solo vertical #################
mask_rshp = tf.tile(tf.cast(mask, tf.float32), [1, 9])
mask_rshp_v = tf.transpose(mask_rshp, [1,0])
mask_rshp   = tf.minimum(1., mask_rshp_v)
mask_rshp

<tf.Tensor: shape=(9, 9), dtype=float32, numpy=
array([[0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.]], dtype=float32)>

In [27]:
############# Daniel vertical + horizontal #################
mask_rshp = tf.tile(tf.cast(mask, tf.float32), [1, 9])
mask_rshp_v = tf.transpose(mask_rshp, [1,0])
mask_rshp   = mask_rshp + mask_rshp_v
mask_rshp   = tf.minimum(1., mask_rshp)
mask_rshp

<tf.Tensor: shape=(9, 9), dtype=float32, numpy=
array([[0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [28]:
############# Cristobal vertical + horizontal #################
mask_rshp = tf.tile(tf.cast(mask, tf.float32), [1, 9])
mask_rshp_v = tf.reverse(mask_rshp, axis=[0])
mask_rshp_h = tf.transpose(mask_rshp, [1,0])
mask_rshp   = mask_rshp_v + mask_rshp_h
mask_rshp   = tf.minimum(1., mask_rshp)
mask_rshp

<tf.Tensor: shape=(9, 9), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.]], dtype=float32)>

In [7]:
# PAPER: Positional encoding
mask_rshp = tf.tile(tf.cast(mask, tf.float32), [1,9])
mask_rshp += tf.transpose(mask_rshp, [1,0])
mask_rshp = tf.minimum(1., mask_rshp)
mask_rshp

<tf.Tensor: shape=(9, 9), dtype=float32, numpy=
array([[0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>